### ISSUE TITLE
导出数据不正确

### ISSUE THREAD

**Issue by hgrourou** [xieguanhua/xmindParser#1]
导出的时候导出的结构不正确
cidData[parentId] = topic.add({ title: name }).cid();  ==> cidData[id] = topic.add({ title: name }).cid();

最后。感谢大佬提供的方法。 thanks

**Comment by xieguanhua** [comment]
可以发一下数据格式我吗

**Comment by hgrourou** [comment]
@xieguanhua  测试用例导出的用例，数据结构为
![image](https://user-images.githubusercontent.com/11886447/115037467-14579580-9f01-11eb-9791-9353c273198f.png)
导出的xmind打开为
![image](https://user-images.githubusercontent.com/11886447/115037530-23d6de80-9f01-11eb-94ef-cd4de373e026.png)
导出后中心节点只有一个子节点

**Comment by xieguanhua** [comment]
不好意思，周末比较忙，到今天才修复，因为封装的时候以脑图的方式来修改，所以导致数据没有唯一id，更新一下版本就好
![image](https://user-images.githubusercontent.com/29080887/115205714-6b8d7e00-a12c-11eb-8fe2-8ef394f9bce4.png)

**Comment by xieguanhua** [comment]
更新一下组件库就好了
![image](https://user-images.githubusercontent.com/29080887/115205714-6b8d7e00-a12c-11eb-8fe2-8ef394f9bce4.png)
